# Generated by Django 4.2 on 2023-05-01 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='discrict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.discrict'),
        ),
    ]
