# Generated by Django 4.1.7 on 2023-03-12 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='marial_status',
            field=models.CharField(choices=[('M', 'Married'), ('S', 'Single')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 21, 19, 14, 847416)),
        ),
    ]
