# Generated by Django 4.1.7 on 2023-02-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
