# Generated by Django 4.1.7 on 2023-02-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_identitynumber_user_identity_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity_number',
            field=models.IntegerField(unique=True),
        ),
    ]
