# Generated by Django 4.1.7 on 2023-03-04 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_marital_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='marital_status',
            new_name='marial_status',
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 9, 32, 1, 954158)),
        ),
    ]
