# Generated by Django 4.2 on 2023-04-18 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appointment_delete_visitrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 20, 51, 32, 689414)),
        ),
    ]
