# Generated by Django 4.2 on 2023-04-18 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_content_file_alter_appointment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 21, 39, 53, 759541)),
        ),
    ]
