# Generated by Django 4.1.7 on 2023-02-28 19:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_content_visitrequest_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitrequest',
            name='visit_id',
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 22, 44, 52, 94081)),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited', to=settings.AUTH_USER_MODEL),
        ),
    ]
